### ISSUE TITLE
Set up HELM (CI/CD)

### ISSUE THREAD

**Issue by eazeredo** [bcgov/digital_marketplace#213]
As a
I want
So that we can have a smooth deployment process

- [x] Set up build / run in CI
- [x] Set up helm chart
- [x] Dev environment
- [ ] <s>Test environment</s>
- [x] Add Spilo (patorni + pg) to chart
(Production is out of scope.)

**Comment by bdolor** [comment]
What are the implementation details for 'set up HELM'? Will you be leveraging `bcgov/helm-charts`?

**Comment by SteveChapmanBCDX** [comment]
Reviewed with team - tabling this issue until we make a decision on what rebuild option to pursue going forward.  Moving this ticket back to the backlog.

**Comment by mikevespi** [comment]
Current state: 
Deployment to develop namespace is currently working in the sense that it deploys the containers to openshift. The issue is that something in the namespace that isn't a part of my deploy process seems to be affecting the port exposure. I will try to get this working tonight. Currently I'm only handling the app in helm, so I may need to get a patroni instance included in it. As it stands, develop and test just have a postgres instance, not patroni. This will be a decent amount of work but would likely be valuable. Concern is that the marketplace uses an old version of pg so I'm not sure how that will affect the chart I want to use for patroni (I intend on using the CAS patroni chart so that we don't have to maintain our own).

**Comment by mikevespi** [comment]
Update:
Helm chart now includes the BCGov spilo chart to provision patroni and pg. Currently running in the development namespace. All that needs to be done now on that namespace is to copy the data out of the existing PG instance from the old deployment, into the new deployment.

**Comment by eazeredo** [comment]
The CI/CD is working properly in the Dev environment.

Side note:
As we had a major change in the CI/CD process with the addition of Patroni to the Dev environment, the Database needed to be recreated. 
Until this moment, the data migration from the original database to the new one (under Patroni) works but it breaks the sign-in.
This problem will happen only the first time that it run.
**This needed to be solved before moving this CI/CD to the Test and Prod environment.**
